name: Publish new version
run-name: Publish new ${{ inputs.bump }} version from ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Positionals'
        required: true
        type: choice
        default: 'prerelease'
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      preid:
        description: 'Prerelease identifier'
        required: true
        type: choice
        default: 'alpha'
        options:
          - alpha
          - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_PACKAGE_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: "Config npm"
        id: config-npm
        run: |
          npm set @gulabs:registry=https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}
          npm set @gusdk:registry=https://test.gusdk.gu.net
          npm set test.gusdk.gu.net/:_authToken=${{ secrets.GUSDK_TEST_NPM_TOKEN }}
      - run: npm install
      - run: npm run bootstrap
      - name: Version
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          npm version ${{ inputs.bump }} --preid ${{ inputs.preid }} >> $TAG
          git push origin TAG